name: Release Mod

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    steps:
      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: R8jBhfbN
          modrinth-token: ${{ secrets.MODRINTH_API_TOKEN }}

          curseforge-id: 494079
          curseforge-token: ${{ secrets.CURSEFORGE_API_TOKEN }}

          loaders: |
            forge
          game-versions: |
            1.12.2
            
          dependencies: |
            pathfinder-api
